FROM node:18 AS build

WORKDIR /app

COPY package.json  ./

RUN npm install && npm install --legacy-peer-deps

COPY . .

RUN npm run build:dev

FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
